# Generated by Django 5.0.6 on 2024-06-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roupas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tamanho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name="produto",
            name="tamanho",
        ),
        migrations.AddField(
            model_name="produto",
            name="tamanho",
            field=models.ManyToManyField(to="roupas.tamanho"),
        ),
    ]
