# Generated by Django 5.0.6 on 2024-06-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roupas", "0002_tamanho_remove_produto_tamanho_produto_tamanho"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tamanho",
            name="nome",
            field=models.CharField(
                choices=[
                    ("PP", "PP"),
                    ("P", "P"),
                    ("M", "M"),
                    ("G", "G"),
                    ("GG", "GG"),
                    ("Extra GG", "Extra GG"),
                ],
                max_length=10,
            ),
        ),
    ]
