# Generated by Django 5.0.6 on 2024-05-28 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "roupas",
            "0002_cliente_endereco_pedido_pagamento_produto_itempedido_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CupomDesconto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50)),
                (
                    "valor_desconto",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnderecoEntrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rua", models.CharField(max_length=100)),
                ("cidade", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=100)),
                ("cep", models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name="categoria",
            name="data_atualizacao",
        ),
        migrations.RemoveField(
            model_name="categoria",
            name="data_criacao",
        ),
        migrations.RemoveField(
            model_name="categoria",
            name="descricao",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="data_atualizacao",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="data_criacao",
        ),
        migrations.RemoveField(
            model_name="itempedido",
            name="data_atualizacao",
        ),
        migrations.RemoveField(
            model_name="itempedido",
            name="data_criacao",
        ),
        migrations.RemoveField(
            model_name="pagamento",
            name="data_atualizacao",
        ),
        migrations.RemoveField(
            model_name="pagamento",
            name="data_criacao",
        ),
        migrations.AddField(
            model_name="cliente",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="categoria",
            name="nome",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="pagamento",
            name="tipo_pagamento",
            field=models.CharField(
                choices=[
                    ("cartao_credito", "Cartão de Crédito"),
                    ("boleto", "Boleto"),
                    ("pix", "Pix"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Carrinho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="roupas.cliente"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnderecoCobranca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endereco", models.CharField(max_length=255)),
                ("cidade", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=100)),
                ("cep", models.CharField(max_length=20)),
                ("pais", models.CharField(max_length=100)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="roupas.cliente"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricoCompras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                ("data_compra", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="roupas.cliente"
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="roupas.produto"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemCarrinho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField()),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "carrinho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="roupas.carrinho",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="roupas.produto"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="roupas.cliente"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemWishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="roupas.produto"
                    ),
                ),
                (
                    "wishlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="roupas.wishlist",
                    ),
                ),
            ],
        ),
    ]
