# Generated by Django 5.0.6 on 2024-05-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roupas", "0003_cupomdesconto_enderecoentrega_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("logo_url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="categoria",
            name="genero",
            field=models.CharField(
                choices=[("F", "Feminino"), ("M", "Masculino"), ("U", "Unissex")],
                default="U",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="genero",
            field=models.CharField(
                choices=[("F", "Feminino"), ("M", "Masculino"), ("U", "Unissex")],
                default="U",
                max_length=1,
            ),
        ),
    ]
