# Generated by Django 5.0.6 on 2024-05-31 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roupas", "0005_alter_cliente_options_alter_cliente_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enderecoentrega",
            name="cliente",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="enderecoentrega",
            name="endereco",
            field=models.CharField(default="Seu valor padrão aqui", max_length=255),
        ),
        migrations.AlterField(
            model_name="enderecocobranca",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enderecos_cobranca",
                to="roupas.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="enderecoentrega",
            name="cep",
            field=models.CharField(max_length=20),
        ),
    ]
