# Generated by Django 5.0.6 on 2024-05-31 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roupas", "0006_enderecoentrega_cliente_enderecoentrega_endereco_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cliente",
            old_name="user",
            new_name="nome",
        ),
    ]
