# Generated by Django 5.0.6 on 2024-06-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roupas', '0007_rename_user_cliente_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nome',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='itemwishlist',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
