# Generated by Django 5.0.6 on 2024-06-02 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roupas', '0008_rename_nome_cliente_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecocobranca',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos_cobranca', to=settings.AUTH_USER_MODEL),
        ),
    ]
